### ISSUE TITLE
Is this repository abandoned

### ISSUE THREAD

**Issue by kmolerov** [soukoku/ntwain#10]
Hello, do you plan to work on this repository in the future, as there is nothing new from Nov.2018. Also the repo in bitbucket is dead from the same date.

**Comment by TiberiusDRAIG** [comment]
Bump. I noticed that v3 doesn't work with TWAIN 2.4.x, and it looks like v4 was spun-up to support it, but if this has indeed been abandoned then I don't really want to invest too much time integrating with it.

**Comment by F1schk0pp** [comment]
It is not abandoned :)
See branch v4
