### ISSUE TITLE
Twain support Win10

### ISSUE THREAD

**Issue by dylsmith8** [soukoku/ntwain#15]
Hi, might be a silly question (new to the twain/printer driver world). In an existing WinForms app, NTwain is used but having issues on certain Windows 10 machines where the `GetSources()` call returns nothing, even though a Twain compatible scanner is installed on the machine. Using a tool like Twacker (https://github.com/twain/twain-toolkit/tree/master/twacker) picks up the device no problem.

I've seen certain posts online about Windows 10 no longer supporting Twain but nothing official from Microsoft. Is this rubbish or something that is an issue. Perhaps you can shed more light. I'd appreciate that :)

**Comment by soukoku** [comment]
Probably the app is running in 64 bit. Most twain drivers are still 32 bit only and are not visible if app is not the same. Twain is definitely supported on Windows 10.

**Comment by dylsmith8** [comment]
Yes it does seem to be the architecture - will poke around some more, thanks!
