### ISSUE TITLE
Display scaling issues

### ISSUE THREAD

**Issue by darko1979** [soukoku/ntwain#17]
I'm on Windows 10 and when display scaling is active executing following lines resets display scaling to 100% for current application.

```
            var appId = TWIdentity.CreateFromAssembly(DataGroups.Image, Assembly.GetExecutingAssembly());
            var session = new TwainSession(appId);
            session.Open();
```
Did anybody else encounter this issue and found a solution?

**Comment by soukoku** [comment]
You can try to declare the app as high DPI aware by putting these in an app manifest file like below. You may have to use other values depending on whether it actually supports high DPI (see [the docs](https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process)).

```xml
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>
    </windowsSettings>
  </application>
```

**Comment by darko1979** [comment]
Thanks, it worked.
