### ISSUE TITLE
How to hide dialog of device when using NTWAIN with Windows Service?

### ISSUE THREAD

**Issue by lnvu1983** [soukoku/ntwain#19]
Anyone know the way to by pass the dialog of device displayed when scanning? It's ok if there is no problem during scan. But if there is an error (ex: PaperJam or No Paper, ...), this will hang the windows service (the dialog require user to take an action to close)

Sample error dialog of device:

![kodak-error](https://user-images.githubusercontent.com/56082274/111296399-03f09880-867f-11eb-8027-c633f94d7127.png)

Tks a lot

**Comment by soukoku** [comment]
If the scanner supports it, you can try setting CAP_INDICATORS to false through `Capabilities.CapIndicators.SetValue()` on the source.

**Comment by lnvu1983** [comment]
> If the scanner supports it, you can try setting CAP_INDICATORS to false through `Capabilities.CapIndicators.SetValue()` on the source.

Thanksssssssssssss, work like a charm. Love you so much :)
