### ISSUE TITLE
Use LibraryImport instead of DllImport in v4

### ISSUE THREAD

**Issue by F1schk0pp** [soukoku/ntwain#36]
Hi @soukoku and thanks a lot for your effort into NTwain.

Beginning with .NET 7 there is a SourceGenerator for P/Invokes.

https://learn.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke-source-generation

It might be a good thing to use this in v4.

What's your opinion about this?

**Comment by soukoku** [comment]
That is interesting. I'll see what I can do.
