### ISSUE TITLE
Unable to use NTwain 3.7.3 NuGet package due to no strong-name

### ISSUE THREAD

**Issue by JoshuaBurrows** [soukoku/ntwain#56]
Hi,

I'm attempting to use the NTwain package in a project that is strong-named and get the following exception.

![Exception](https://github.com/soukoku/ntwain/assets/113096350/8ad01088-2feb-4d09-8f16-81e4c6429c57)

Just wondering if it would be possible to add a strong-name to the assembly?

Thanks in advance.

**Comment by soukoku** [comment]
I added a 3.7.4 that should have it.

**Comment by JoshuaBurrows** [comment]
Great, I've just updated the package and the issue has been resolved.
I appreciate the quick fix!

Thanks.
